### PR TITLE
Set up is two words

### PR DESCRIPTION
**Pull request by RichardLitt**
Setup, as a compound word, normally is the noun. Set up is the normal verb, in my experience.

### CODE REVIEW

**Comment by DougInAMug** [comment]
Hmm. I think 'setup' has become normalized, and even if not 'normal', it's not wrong: https://www.merriam-webster.com/dictionary/setup?src=search-dict-hed

**Comment by RichardLitt** [comment]
Not for the verb. From the link to MW you posted:

> the verb set up, on the other hand, is usually found as an open compound (two words, no hyphen) in both American and British English.

**Comment by DougInAMug** [comment]
Ah, yes. I agree with you, although I don't think it's beyond the fluidic scope of English to accommodate ;p

**Comment by RichardLitt** [comment]
Oh, I agree. The question for me is: will people stop when reading this and notice? I did. That's not ideal. We want people focusing on the content, not skipping over odd spelling choices.

**Pull request merged**
